# Generated by Django 2.1.7 on 2019-03-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
