# Generated by Django 2.1.7 on 2019-03-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20190324_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='c_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='f_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
