# Generated by Django 2.1.7 on 2019-03-04 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 5, 47, 41, 603391, tzinfo=utc)),
        ),
    ]
