# Generated by Django 2.1.7 on 2019-03-24 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0003_auto_20190304_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 23, 7, 52, 269909, tzinfo=utc)),
        ),
    ]
