# Generated by Django 2.1.7 on 2019-03-25 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0004_auto_20190324_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 3, 53, 7, 686024, tzinfo=utc)),
        ),
    ]
