# Generated by Django 2.1.7 on 2019-03-25 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0005_auto_20190325_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 4, 12, 13, 104309, tzinfo=utc)),
        ),
    ]
