# Generated by Django 2.1.7 on 2019-03-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0002_auto_20190304_0547'),
        ('mealbuilder', '0005_auto_20190325_0353'),
    ]

    operations = [
    ]
