# Generated by Django 2.1.7 on 2019-03-25 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0006_auto_20190325_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_proportion', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='num_of_meals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='creator_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(default='Meal Name', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 5, 7, 9, 587011, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mealbuilder.Food'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mealbuilder.Meal'),
        ),
    ]
