# Generated by Django 2.1.7 on 2019-03-25 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0006_merge_20190325_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='fruit', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='db_num',
            field=models.CharField(default='-1', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 16, 13, 0, 395607, tzinfo=utc)),
        ),
    ]
