# Generated by Django 2.1.7 on 2019-03-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0008_auto_20190325_0523'),
        ('mealbuilder', '0007_auto_20190325_1614'),
    ]

    operations = [
    ]
