# Generated by Django 2.1.7 on 2019-03-30 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0009_merge_20190330_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealitem',
            old_name='food_proportion',
            new_name='food_portion',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fiber',
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 19, 15, 33, 775143, tzinfo=utc)),
        ),
    ]
