# Generated by Django 2.1.7 on 2019-03-30 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0013_auto_20190330_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carb_goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat_goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein_goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 23, 7, 58, 952474, tzinfo=utc)),
        ),
    ]
