# Generated by Django 2.1.7 on 2019-03-31 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0015_auto_20190331_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 0, 40, 32, 386174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mealbuilder.Food'),
            preserve_default=False,
        ),
    ]
