# Generated by Django 2.1.7 on 2019-03-31 01:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0017_auto_20190331_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 1, 35, 49, 695386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
