# Generated by Django 2.1.7 on 2019-04-15 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0026_auto_20190414_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 3, 32, 26, 468589, tzinfo=utc)),
        ),
    ]
